### ISSUE TITLE
Iniciar debe volver a funcionar 

### ISSUE THREAD

**Issue by canek-pelaez** [yinwm88/Repertorio-de-recetas#6]
El inicio de sesión funcionaba antes, debe volver a hacerlo.

**Comment by yinwm88** [comment]
¡Listo!Fue un error de endpoint donde se indicò mal el puerto.

app/frontend/src/Componentes/LP/Ingreso.js

`     -  const response = await fetch('http://localhost:**3000**/join/registrarse', { `
` 60  +  const response = await fetch('http://localhost:**3030**/join/registrarse', { `

**Comment by yinwm88** [comment]
¡Listo!Fue un error de endpoint donde se indicò mal el puerto.

app/frontend/src/Componentes/LP/Ingreso.js

`       -  const response = await fetch('http://localhost:**3000**/join/registrarse', { `  
`   60  +  const response = await fetch('http://localhost:**3030**/join/registrarse', { `

**Comment by yinwm88** [comment]
¡Listo!Fue un error de endpoint donde se indicò mal el puerto.

app/frontend/src/Componentes/LP/Ingreso.js

 `     -  const response = await fetch('http://localhost:3000/join/registrarse', {` 
 `  60  +  const response = await fetch('http://localhost:3030/join/registrarse', {`

**Comment by canek-pelaez** [comment]
Si al menos existiera un mecanismo donde se pudiera probar automáticamente si los cambios al sistema funcionan o no...
