### ISSUE TITLE
Investigar cómo simplificar la consulta de recetas 

### ISSUE THREAD

**Issue by canek-pelaez** [yinwm88/Repertorio-de-recetas#8]
Ver si es posible simplificar la generación de recetas.

**Comment by ErickSonico** [comment]
Se crearon dos consultas más sencillas para obtener los ingredientes del usuario y los de todas las recetas, luego se comparan. Esta solución permite que se agregen más condiciones para generar las recetas, lo que nos facilitará la parte de los filtros.  Se puede ver en la rama front-back.
